# python_9_numpy_scipy

In [2]:
import numpy as np

Матрица в виде numpy array

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [3]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [4]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [10]:
for user in users_stats:
    a = np.array(user)
    b = next_user_stats
    c = cosine(a,b)
    print(user, format(c, ".2f"))

[2 1 0 0 0 0] 0.20
[1 1 2 1 0 0] 0.85
[2 0 1 0 0 0] 0.40
[1 1 2 1 0 1] 0.79
[0 0 1 2 0 0] 0.40
[0 0 0 0 0 5] 0.00
[1 0 0 0 0 0] 0.00
[0 1 1 0 0 0] 0.95
[0 0 0 1 1 3] 0.00
[1 0 0 2 1 4] 0.00


Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [32]:
a = np.arange(0, 10)[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [36]:
a = np.diag(np.arange(0, 10)[::-1])
a

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
np.trace(a)

45

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [3]:
a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [4]:
from numpy import linalg

In [5]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [17]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True